version: '3.7'
services:
    fieldsets-redis:
        image: ${CONTAINER_REGISTRY:-fieldsets}/docker-redis:${REDIS_VERSION:-latest}
        build:
            context: ./
            dockerfile: ${REDIS_CONFIG_PATH:-./}Dockerfile
            args:
                REDIS_VERSION: ${REDIS_VERSION:-latest}
        container_name: fieldsets-redis
        hostname: fieldsets-redis
        ports:
            - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
        #command: redis-server --requirepass ${REDIS_PASSWORD:-fieldsets}
        environment:
            REDIS_HOST: ${REDIS_HOST:-172.28.0.2}
            REDIS_PORT: ${REDIS_PORT:-6379}
        volumes:
            #- ${REDIS_CONFIG_PATH:-./}redis.conf:/etc/redis.conf
            - redis-data:/data
            - redis-modules:/modules
        networks:
            default:
                ipv4_address: ${REDIS_HOST:-172.28.0.10}

volumes:
    redis-data:
        driver: local
        name: fieldsets-redis-data
    redis-modules:
        driver: local
        name: fieldsets-redis-modules

networks:
    default:
        driver: bridge
        name: fieldsets_network
        attachable: true
        ipam:
            config:
            - subnet: ${FIELDSETS_LOCAL_NETWORK_SUBNET:-172.28.0.0/24}


